alertmanager:
  extraArgs:
    cluster.advertise-address: "$(POD_IP):9094"
  persistence:
    enabled: true
    storageClass: "gp2"  # Specify your custom StorageClass here. Using the one which was cxreated as part of addon installation
    size: 10Gi  # Define the storage size you want
server:
  persistentVolume:
    enabled: true
    storageClass: "gp2"  # Specify your custom StorageClass here. Using the one which was cxreated as part of addon installation
    size: 10Gi  # Define the storage size you want

# This section of ingress is not working so I have created the ingress resource using directly yaml file instead of helm chart
#ingress:
  #enabled: true
  #ingressClassName: alb  # Specify ALB as the ingress controller
  
  ## Add necessary annotations for ALB
  #annotations:
   # alb.ingress.kubernetes.io/scheme: internet-facing  # Use "internal" if private
   # alb.ingress.kubernetes.io/target-type: ip  # Target type is IP
   # alb.ingress.kubernetes.io/group.name: prometheus-group  # Optional, groups ALB resources
   #alb.ingress.kubernetes.io/healthcheck-path: "/"  # Health check path
   # alb.ingress.kubernetes.io/success-codes: "200,302"  # Success codes for health check
  
  ## Define hostnames for the Ingress
  #hosts:
    #- host: prometheus.example.com  # Replace with your actual domain
     #paths:
     #   - path: /  # Path for the ingress
      #    pathType: Prefix  # Path type is Prefix