apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: custom
spec:

  # Required: Name of IAM Role for Nodes
  role: "AmazonEKSAutoNodeRole"

  # Required: Subnet selection for node placement
  subnetSelectorTerms:
    - tags:
        kubernetes.io/role/internal-elb: "1"
    # Alternative using direct subnet ID
    # - id: "subnet-0123456789abcdef0"

  # Required: Security group selection for nodes
  securityGroupSelectorTerms:
    - name: "eks-cluster-sg-eks-100493"

    # Alternative approaches:
    # - id: "sg-0123456789abcdef0"
    # - name: "eks-cluster-node-security-group"